name: build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install test framework
        run: make -C tests install
      - name: Test
        run: make -C tests
  build-with-make-cmake:
    name: Build with Make and CMake
    runs-on: ubuntu-latest
    needs: [unit-test]
    container:
      image: libmcu/ci:latest
    strategy:
      matrix:
        include:
          - target: stm32_min_dev_blue
            repo: STMicroelectronics/STM32CubeF1
            path: ${{ github.event.repository.name }}/external/STM32CubeF1
          - target: nrf52_libmcu
            repo: libmcu/nRF5_SDK_17.1.0_ddde560
            path: ${{ github.event.repository.name }}/external/nRF5_SDK_17.1.0_ddde560
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          submodules: recursive
          path: ${{ github.event.repository.name }}
      - name: Clone the dependancies
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo }}
          path: ${{ matrix.path }}
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: Build with Make
        run: |
          make -C ${{ github.event.repository.name }} BOARD=${{ matrix.target }}
          make -C ${{ github.event.repository.name }} clean
      - name: Build with CMake
        run: |
          cmake -S ${{ github.event.repository.name }} -B build \
                -DBOARD=${{ matrix.target }} \
                -DCMAKE_TOOLCHAIN_FILE=projects/arm-none-eabi-gcc.cmake
          cmake --build build
  build-for-esp32-with-esp-idf:
    name: Build for ESP32 with ESP-IDF
    runs-on: ubuntu-latest
    needs: [unit-test]
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build on v4.4
        uses: docker://espressif/idf:release-v4.4
        with:
          args: /bin/bash -c "git config --global --add safe.directory /github/workspace && idf.py set-target esp32s3 && idf.py build"
      - name: Build on latest
        uses: docker://espressif/idf:latest
        with:
          args: /bin/bash -c "git config --global --add safe.directory /github/workspace && rm -rf build sdkconfig && idf.py set-target esp32s3 && idf.py build"
  build-with-zephyr:
    name: Build with Zephyr
    strategy:
      matrix:
        target: [esp32]
    runs-on: ubuntu-latest
    needs: [unit-test]
    container:
      image: zephyrprojectrtos/ci:latest
    env:
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk-0.15.2
    steps:
      - name: Prepare
        run: |
          west init .
          west update
      - name: Clone
        uses: actions/checkout@v3
        with:
          submodules: recursive
          path: ${{ github.event.repository.name }}
      - name: Build for ${{ matrix.target }}
        run: west build -b ${{ matrix.target }} ${{ github.event.repository.name }} -p always
